# Generated by Django 3.2.2 on 2021-08-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alertmatch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="match_count",
        ),
    ]
