version: "3.9"

services:
  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
      - /fleebmarket_blue/services/graphite/conf:/opt/graphite/conf
      - /data/graphite/:/opt/graphite/storage
    ports:
      - 8080:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
