# Generated by Django 3.2.2 on 2021-08-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_alter_redditadvert_ad_type'),
        ('alerts', '0002_rename_sensitiviy_alert_sensitivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_app.redditadvert')),
                ('alert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alert')),
            ],
        ),
    ]
