# Generated by Django 3.2.2 on 2021-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_remove_alert_match_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="sensitivity",
            field=models.IntegerField(),
        ),
    ]
