version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v0.27.1
    environment: 
      MEILI_DB_PATH: /meilifiles
    volumes:
      - meilisearch:/meilifiles
    ports:
      - 7700:7700

volumes:
  meilisearch:
