# Generated by Django 3.2.2 on 2021-08-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        # Commented out because makes test bug
#         migrations.RunSQL(
#             """
# INSERT INTO search_app_redditadvert (SELECT * from search_ads_redditadvert)
#             """
#         )
    ]
