# Generated by Django 3.2.2 on 2021-12-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0004_alter_redditadvert_ad_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedditAdvertItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                ("sold", models.BooleanField()),
                ("full_text", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                (
                    "reddit_advert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search_app.redditadvert",
                    ),
                ),
            ],
        ),
    ]
