# Generated by Django 3.2.2 on 2022-01-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0005_redditadvertitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditadvert",
            name="is_duplicate",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="redditadvert",
            name="author",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
