# Generated by Django 3.2.2 on 2022-06-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0006_auto_20220123_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redditadvert",
            name="last_updated",
            field=models.DateTimeField(db_index=True),
        ),
    ]
