# Generated by Django 3.2.2 on 2022-07-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0007_alter_redditadvert_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="redditadvert",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
